---
apiVersion: v1
kind: Pod
metadata:
  name: test-s3-mount
  namespace: limanEKS-api-staging
spec:
  containers:
    - name: app
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from the container!' >> /data/test/froi-Mount.txt; tail -f /dev/null"]
      volumeMounts:
        - name: test
          mountPath: /data
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: limanEKS-s3-pvc